package it.ctinnovation.droolsbridge.props;

import org.springframework.boot.context.properties.ConfigurationProperties;

@ConfigurationProperties(prefix = "drools")
public class DroolsConfigProps {
	private String ruleGroupID;
	private String ruleArtifactId;
	private String ruleVersion;
	private String kieBaseName;
	private String kieSessionName;
	private Long kieScannerInterval;
	private boolean customKieScanner;
	private String alertTtlMeasUnit;
	private Boolean statisticEnabled = true;
	private int statisticFreqRatio = 10;
	private Boolean logEnabled = false;
	private Boolean debugEnabled = false;
	private String logFile;

	//region Getters and setters
	public String getRuleGroupID() {
		return ruleGroupID;
	}

	public void setRuleGroupID(String ruleGroupID) {
		this.ruleGroupID = ruleGroupID;
	}

	public String getRuleArtifactId() {
		return ruleArtifactId;
	}

	public void setRuleArtifactId(String ruleArtifactId) {
		this.ruleArtifactId = ruleArtifactId;
	}

	public String getRuleVersion() {
		return ruleVersion;
	}

	public void setRuleVersion(String ruleVersion) {
		this.ruleVersion = ruleVersion;
	}

	public Long getKieScannerInterval() {
		return kieScannerInterval;
	}

	public boolean isCustomKieScanner() {
		return customKieScanner;
	}

	public void setCustomKieScanner(boolean customKieScanner) {
		this.customKieScanner = customKieScanner;
	}

	public void setKieScannerInterval(Long kieScannerInterval) {
		this.kieScannerInterval = kieScannerInterval;
	}

	public String getKieSessionName() {
		return kieSessionName;
	}

	public void setKieSessionName(String kieSessionName) {
		this.kieSessionName = kieSessionName;
	}

	public String getKieBaseName() {
		return kieBaseName;
	}

	public void setKieBaseName(String kieBaseName) {
		this.kieBaseName = kieBaseName;
	}

	public String getAlertTtlMeasUnit() {
		return alertTtlMeasUnit;
	}

	public void setAlertTtlMeasUnit(String alertTtlMeasUnit) {
		this.alertTtlMeasUnit = alertTtlMeasUnit;
		if (alertTtlMeasUnit == null)
			alertTtlMeasUnit = "M";
	}
	public Boolean getStatisticEnabled() {
		return statisticEnabled;
	}

	/**
	 * Enable / disable the inclusion in the Report topic the Drools statistic on active Facts generated by the DRL Queries.
	 *
	 * @param statisticEnabled
	 */
	public void setStatisticEnabled(Boolean statisticEnabled) {
		this.statisticEnabled = statisticEnabled;
	}

	public int getStatisticFreqRatio() {
		return statisticFreqRatio;
	}

	public void setStatisticFreqRatio(int statisticFreqRatio) {
		this.statisticFreqRatio = statisticFreqRatio;
	}

	public Boolean getLogEnabled() {
		return logEnabled;
	}

	/**
	 * Enable / disable the Drools internal KieRuntimeLogger
	 *
	 * @param logEnabled
	 */
	public void setLogEnabled(Boolean logEnabled) {
		this.logEnabled = logEnabled;
	}

	public String getLogFile() {
		return logFile;
	}

	public void setLogFile(String logFile) {
		this.logFile = logFile;
	}

	public Boolean getDebugEnabled() {
		return debugEnabled;
	}

	/**
	 * Enable / disable the debug drools agenda listener
	 *
	 * @param debugEnabled
	 */
	public void setDebugEnabled(Boolean debugEnabled) {
		this.debugEnabled = debugEnabled;
	}

	//endregion
}
